export const CLINICAL_CATEGORIES = [
  "Cardiologia",
  "Pneumologia",
  "Gastro/Hepato",
  "Nefro/Uro",
  "Endocrino/Metabolico",
  "Infectologia",
  "Reumatologia/Ortopedia",
  "Dermatologia",
  "Neurologia",
  "Psiquiatria",
  "Gineco/Obstetricia",
  "Pediatria Geral",
  "Trauma/Urgencia",
  "Toxicologico",
  "Oftalmologia/Otorrino",
  "Hematologia",
  "Oncologia",
  "Outros",
] as const;

export type ClinicalCategory = typeof CLINICAL_CATEGORIES[number];

interface PathologyData {
  name: string;
  clinicalCategory: ClinicalCategory;
  ageGroup: "adulto" | "pediatrico";
  sourceGroup: string;
}

export const adultoBasePathologies: PathologyData[] = [
  { name: "Insuficiência Cardíaca Descompensada", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome Coronariana Aguda / Infarto Agudo do Miocárdio", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Fibrilação Atrial / Flutter Atrial", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Crise Hipertensiva (Urgência e Emergência)", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Trombose Venosa Profunda", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Embolia Pulmonar", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Edema Agudo de Pulmão Cardiogênico", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Bradicardias sintomáticas", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Taquiarritmias supraventriculares e ventriculares", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Pneumonia Adquirida na Comunidade", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Pneumonia Nosocomial / Associada à Ventilação", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Exacerbação de Asma / Crise Asmática", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Exacerbação de DPOC", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Insuficiência Respiratória Aguda", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome do Desconforto Respiratório Agudo (SDRA)", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Derrame Pleural", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Pneumotórax", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hemoptise", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hemorragia Digestiva Alta e Baixa", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Cirrose Hepática Descompensada (Ascite, Encefalopatia)", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Pancreatite Aguda", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Colecistite / Colangite Aguda", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hepatite Aguda", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Doença Inflamatória Intestinal (Crohn e Retocolite)", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Abdome Agudo (Obstrutivo, Perfurativo, Inflamatório)", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Diarreia Aguda Infecciosa", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Injúria Renal Aguda (Pré, Renal e Pós-renal)", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Doença Renal Crônica Agudizada", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome Nefrótica e Nefrítica", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Distúrbios Hidroeletrolíticos (Hipo/Hipernatremia, Hipo/Hipercalemia)", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Distúrbios Ácido-Básicos", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Infecção do Trato Urinário Alta e Baixa (Pielonefrite, Cistite)", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Cólica Nefrética / Nefrolitíase", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Retenção Urinária Aguda", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Cetoacidose Diabética", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Estado Hiperglicêmico Hiperosmolar", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hipoglicemia Grave", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Crise Tireotóxica / Tempestade Tireoidiana", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Coma Mixedematoso", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Insuficiência Adrenal Aguda (Crise Adrenal)", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hipercalcemia Grave", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Sepse e Choque Séptico", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Meningite Bacteriana", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Endocardite Infecciosa", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Infecções de Pele e Partes Moles (Celulite, Erisipela, Fasciíte)", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Dengue / Dengue Grave", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Chikungunya", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Malária Grave", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Leptospirose", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Tuberculose Pulmonar e Extrapulmonar", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Infecções em Imunossuprimidos", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "HIV/AIDS (Infecções Oportunistas)", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "COVID-19 e suas complicações", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Artrite Séptica", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Osteomielite Aguda", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Crise de Gota Aguda", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Lúpus Eritematoso Sistêmico Ativo", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Vasculites Sistêmicas", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Miopatias Inflamatórias (Dermatomiosite, Polimiosite)", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Urticária e Angioedema Agudo", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome de Stevens-Johnson / Necrólise Epidérmica Tóxica", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Pênfigos", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Herpes Zoster e complicações", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Reações Medicamentosas Cutâneas Graves (DRESS, AGEP)", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Acidente Vascular Encefálico Isquêmico e Hemorrágico", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hemorragia Subaracnóidea", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Convulsões e Estado de Mal Epiléptico", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Encefalopatia Hepática / Urêmica / Metabólica", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome de Guillain-Barré", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Miastenia Gravis (Crise Miastênica)", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Cefaleia Aguda Grave (Investigação de causas secundárias)", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Rebaixamento do Nível de Consciência / Coma", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Delirium / Estado Confusional Agudo", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome de Abstinência Alcoólica (Delirium Tremens)", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome de Abstinência de Opioides", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome Neuroléptica Maligna", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome Serotoninérgica", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Tentativa de Suicídio e Auto-lesão (Manejo Clínico)", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Pré-eclâmpsia / Eclâmpsia", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome HELLP", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hemorragia Obstétrica (Pré e Pós-parto)", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Doença Inflamatória Pélvica", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Aborto Séptico", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Gravidez Ectópica Rota", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Politraumatizado", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Traumatismo Cranioencefálico", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Trauma Torácico (Pneumotórax, Hemotórax, Contusão Pulmonar)", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Trauma Abdominal", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Choque Hemorrágico", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Grandes Queimados", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Parada Cardiorrespiratória e Pós-Ressuscitação", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Afogamento", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Hipotermia Grave / Hipertermia Grave", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Intoxicação Exógena Geral (Abordagem inicial)", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Intoxicação por Paracetamol", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Intoxicação por Organofosforados (Carbamatos)", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Intoxicação por Benzodiazepínicos / Opioides", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Intoxicação por Cocaína / Simpatomiméticos", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Acidentes por Animais Peçonhentos (Ofídico, Escorpiônico, Araneísmo)", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Anafilaxia", clinicalCategory: "Outros", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Trombocitopenia Imune (Púrpura Trombocitopênica)", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Anemia Hemolítica Aguda", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Coagulação Intravascular Disseminada (CIVD)", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Neutropenia Febril", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome de Lise Tumoral", clinicalCategory: "Oncologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Compressão Medular Neoplásica", clinicalCategory: "Oncologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
  { name: "Síndrome da Veia Cava Superior", clinicalCategory: "Oncologia", ageGroup: "adulto", sourceGroup: "adulto_base" },
];

export const pediatricoBasePathologies: PathologyData[] = [
  { name: "Bronquiolite Viral Aguda", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Pneumonia Comunitária Pediátrica", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Crise de Asma em Pediatria", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Laringite / Crupe Viral", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Rinossinusite Aguda", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Otite Média Aguda", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Coqueluche / Síndrome Coqueluchoide", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Insuficiência Respiratória Aguda Pediátrica", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Gastroenterite Aguda / Desidratação", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Dor Abdominal Aguda Pediátrica", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Apendicite Aguda", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Invaginação Intestinal", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Icterícia Neonatal", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Hepatite Aguda Pediátrica", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Cetoacidose Diabética em Crianças", clinicalCategory: "Endocrino/Metabolico", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Hipoglicemia Neonatal e Pediátrica", clinicalCategory: "Endocrino/Metabolico", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Distúrbios Eletrolíticos em Pediatria", clinicalCategory: "Nefro/Uro", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Infecção do Trato Urinário Pediátrica", clinicalCategory: "Nefro/Uro", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Síndrome Nefrótica Pediátrica", clinicalCategory: "Nefro/Uro", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Glomerulonefrite Pós-Estreptocócica", clinicalCategory: "Nefro/Uro", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Injúria Renal Aguda Pediátrica", clinicalCategory: "Nefro/Uro", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Sepse Pediátrica / Neonatal", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Meningite Bacteriana Pediátrica", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Encefalite Viral", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Celulite / Erisipela em Crianças", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Artrite Séptica Pediátrica", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Osteomielite Pediátrica", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Dengue / Dengue Grave em Crianças", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "COVID-19 em Pediatria e Síndrome Inflamatória Multissistêmica (MIS-C)", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Tuberculose Pediátrica", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Varicela e Complicações", clinicalCategory: "Infectologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Doença de Kawasaki", clinicalCategory: "Cardiologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Miocardite Aguda Pediátrica", clinicalCategory: "Cardiologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Cardiopatias Congênitas Descompensadas", clinicalCategory: "Cardiologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Insuficiência Cardíaca Pediátrica", clinicalCategory: "Cardiologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Arritmias Pediátricas", clinicalCategory: "Cardiologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Crise Convulsiva Febril", clinicalCategory: "Neurologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Estado de Mal Epiléptico Pediátrico", clinicalCategory: "Neurologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Hidrocefalia Aguda / Disfunção de Derivação", clinicalCategory: "Neurologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Encefalopatia Hipóxico-Isquêmica Neonatal", clinicalCategory: "Neurologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "AVC Pediátrico", clinicalCategory: "Neurologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Púrpura de Henoch-Schönlein", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Artrite Idiopática Juvenil em Atividade", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Febre Reumática Aguda", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Lúpus Eritematoso Sistêmico Juvenil", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Anafilaxia Pediátrica", clinicalCategory: "Outros", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Urticária Aguda / Angioedema em Crianças", clinicalCategory: "Dermatologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Reação Medicamentosa Grave em Pediatria", clinicalCategory: "Dermatologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Anemia Falciforme (Crise Vaso-oclusiva, Sequestro Esplênico)", clinicalCategory: "Hematologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Anemia Hemolítica em Crianças", clinicalCategory: "Hematologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Púrpura Trombocitopênica Imune (PTI) Pediátrica", clinicalCategory: "Hematologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Coagulopatias em Crianças (Hemofilia, Von Willebrand)", clinicalCategory: "Hematologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Neutropenia Febril Pediátrica", clinicalCategory: "Hematologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Síndrome de Lise Tumoral Pediátrica", clinicalCategory: "Oncologia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Trauma Pediátrico (TCE, Abdominal, Torácico)", clinicalCategory: "Trauma/Urgencia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Queimaduras Pediátricas", clinicalCategory: "Trauma/Urgencia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Afogamento em Crianças", clinicalCategory: "Trauma/Urgencia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Parada Cardiorrespiratória Pediátrica", clinicalCategory: "Trauma/Urgencia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Corpo Estranho em Vias Aéreas / Esôfago", clinicalCategory: "Trauma/Urgencia", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Intoxicação Exógena Pediátrica", clinicalCategory: "Toxicologico", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Síndrome de Maus-Tratos / Criança Vítima de Violência", clinicalCategory: "Outros", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Desnutrição Grave", clinicalCategory: "Pediatria Geral", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Distúrbios Metabólicos Congênitos", clinicalCategory: "Endocrino/Metabolico", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Hipotireoidismo e Hipertireoidismo Pediátrico", clinicalCategory: "Endocrino/Metabolico", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
  { name: "Insuficiência Adrenal Pediátrica", clinicalCategory: "Endocrino/Metabolico", ageGroup: "pediatrico", sourceGroup: "pediatrico_base" },
];

export const outrasPrevalentesPathologies: PathologyData[] = [
  { name: "Hipertensão Arterial Sistêmica", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Diabetes Mellitus Tipo 2 (Descompensado)", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Doença do Refluxo Gastroesofágico", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Lombalgia Aguda / Crônica", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Cervicalgia / Síndrome Miofascial", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Osteoartrite", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Enxaqueca / Migrânea", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Cefaleia Tensional", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Vertigem / Labirintopatia (VPPB, Neurite Vestibular)", clinicalCategory: "Oftalmologia/Otorrino", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Zumbido / Tinnitus", clinicalCategory: "Oftalmologia/Otorrino", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Conjuntivite", clinicalCategory: "Oftalmologia/Otorrino", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Faringoamigdalite Aguda", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Sinusite Aguda / Crônica", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Rinite Alérgica", clinicalCategory: "Outros", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Dermatite Atópica", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Dermatite de Contato", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Psoríase", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Micoses Superficiais (Tinea)", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Impetigo", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Foliculite / Abscesso Cutâneo", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Herpes Simples (Oral / Genital)", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Transtorno de Ansiedade Generalizada", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Transtorno de Pânico", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Episódio Depressivo Agudo", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Insônia", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Constipação Intestinal Crônica", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Síndrome do Intestino Irritável", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Dispepsia Funcional", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Doença Hemorroidária", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Fissura Anal", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Candidíase Vaginal / Vaginose Bacteriana", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Infecções Sexualmente Transmissíveis (ISTs)", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Dismenorreia", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Infecções Virais Inespecíficas (Virose)", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Dor Torácica Atípica (Não cardíaca)", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Fibromialgia", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Anemia Ferropriva", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Anemia Megaloblástica", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Hiperuricemia Assintomática", clinicalCategory: "Reumatologia/Ortopedia", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Obesidade / Síndrome Metabólica", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Hipotireoidismo / Hipertireoidismo", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Dislipidemia", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
  { name: "Cistite não complicada", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "outras_prevalentes" },
];

export const plantaoUrgenciaPathologies: PathologyData[] = [
  { name: "Parada Cardiorrespiratória (PCR) e Manejo Pós-PCR", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Choque (Hipovolêmico, Distributivo, Cardiogênico, Obstrutivo)", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Sepse e Choque Séptico", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Síndrome Coronariana Aguda (IAM com e sem supra de ST)", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Edema Agudo de Pulmão Cardiogênico", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Crise Hipertensiva (Urgência vs Emergência)", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Arritmias Graves (FA de alta resposta, TV sustentada, bradicardia sintomática)", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Embolia Pulmonar", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Tamponamento Cardíaco", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Dissecção Aórtica", clinicalCategory: "Cardiologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Insuficiência Respiratória Aguda", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Crise de Asma Grave / Estado de Mal Asmático", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Exacerbação Grave de DPOC", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Pneumotórax Hipertensivo", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hemoptise Maciça", clinicalCategory: "Pneumologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "AVC Isquêmico e Hemorrágico", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hemorragia Subaracnóidea", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Estado de Mal Epiléptico", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hipertensão Intracraniana", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Coma / Rebaixamento do Nível de Consciência", clinicalCategory: "Neurologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hemorragia Digestiva Alta e Baixa", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Abdome Agudo (Obstrutivo, Perfurativo, Vascular)", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Pancreatite Aguda Grave", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Colangite Aguda", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Encefalopatia Hepática Aguda", clinicalCategory: "Gastro/Hepato", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Cetoacidose Diabética (CAD)", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Estado Hiperosmolar Hiperglicêmico (EHH)", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hipoglicemia Grave", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Crise Tireotóxica (Tempestade Tireoidiana)", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Crise Adrenal (Insuficiência Adrenal Aguda)", clinicalCategory: "Endocrino/Metabolico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Distúrbios Graves de Sódio (Hipo/Hipernatremia)", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Distúrbios Graves de Potássio (Hipo/Hipercalemia)", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hipercalcemia Grave", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Injúria Renal Aguda Grave (IRA dialítica)", clinicalCategory: "Nefro/Uro", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Politraumatizado", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Traumatismo Cranioencefálico (TCE) Grave", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Trauma Torácico (Hemotórax, Tórax Instável)", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Trauma Abdominal", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Trauma Raquimedular", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Choque Hemorrágico", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Grande Queimado", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Afogamento / Quase Afogamento", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hipotermia Grave", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hipertermia Grave / Intermação", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Intoxicação Exógena Grave (Geral)", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Intoxicação por Paracetamol", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Intoxicação por Organofosforados/Carbamatos", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Intoxicação por Opioides", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Intoxicação por Cocaína/Simpatomiméticos", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Acidentes com Animais Peçonhentos (Ofídicos, Escorpiônicos, Aranhas)", clinicalCategory: "Toxicologico", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Meningite Bacteriana", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Fasciíte Necrotizante / Gangrena de Fournier", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Dengue Grave / Choque da Dengue", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Malária Grave", clinicalCategory: "Infectologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Anafilaxia", clinicalCategory: "Outros", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Síndrome de Stevens-Johnson / Necrólise Epidérmica Tóxica", clinicalCategory: "Dermatologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Síndrome de Abstinência Alcoólica / Delirium Tremens", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Síndrome Neuroléptica Maligna", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Síndrome Serotoninérgica", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Agitação Psicomotora Grave", clinicalCategory: "Psiquiatria", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Eclâmpsia", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Síndrome HELLP", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Hemorragia Obstétrica Grave (Placenta Prévia, DPP, Atonia)", clinicalCategory: "Gineco/Obstetricia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Neutropenia Febril de Alto Risco", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "CIVD (Coagulação Intravascular Disseminada)", clinicalCategory: "Hematologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Síndrome de Lise Tumoral", clinicalCategory: "Oncologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Compressão Medular Oncológica", clinicalCategory: "Oncologia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Obstrução de Vias Aéreas / Corpo Estranho", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Via Aérea Difícil", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
  { name: "Sequência Rápida de Intubação (SRI)", clinicalCategory: "Trauma/Urgencia", ageGroup: "adulto", sourceGroup: "plantao_urgencia" },
];

export const allPathologies = [
  ...adultoBasePathologies,
  ...pediatricoBasePathologies,
  ...outrasPrevalentesPathologies,
  ...plantaoUrgenciaPathologies,
];
